###########################################################################
JAVA = java
JAVAC = javac

JAR_FILE = ../../../assets/algs4/algs4.jar

Assign02_01: Assign02_01.class;
	$(JAVA) -cp $(CLASS_PATHS) -cp . Assign02_01
Assign02_02: Assign02_02.class;
	$(JAVA) -cp $(CLASS_PATHS) -cp . Assign02_02
Assign02_03: Assign02_03.class;
	$(JAVA) -cp $(CLASS_PATHS) -cp . Assign02_03
Assign02_04: Assign02_04.class;
	$(JAVA) -cp $(CLASS_PATHS) -cp . Assign02_04
Assign02_05: Assign02_05.class;
	$(JAVA) -cp $(CLASS_PATHS) -cp . Assign02_05

Assign02_01.class: Assign02_01.java;
	$(JAVAC) -cp $(CLASS_PATHS) -cp . Assign02_01.java
Assign02_02.class: Assign02_02.java;
	$(JAVAC) -cp $(CLASS_PATHS) -cp . Assign02_02.java
Assign02_03.class: Assign02_03.java;
	$(JAVAC) -cp $(CLASS_PATHS) -cp . Assign02_03.java
Assign02_04.class: Assign02_04.java;
	$(JAVAC) -cp $(CLASS_PATHS) -cp . Assign02_04.java
Assign02_05.class: Assign02_05.java;
	$(JAVAC) -cp $(CLASS_PATHS) -cp . Assign02_05.java

clean:
	rm -f *.class
###########################################################################
###########################################################################
###########################################################################

